layout(std430, binding = 2) buffer CameraBuffer
{
    Transform transform;
    vec3 viewParams;
} Camera;

Ray createCameraRayFromUV(vec2 uv)
{
    vec3 localPoint = vec3(uv - 0.5, 1) * Camera.viewParams;
    vec3 viewPoint = (Camera.transform.localToWorld * vec4(localPoint, 1.0)).xyz;

    Ray ray;
    ray.origin = position(Camera.transform.localToWorld);
    ray.direction = normalize(viewPoint - ray.origin);

    return ray;
}