vec3 transformVector(vec3 vector, mat4 transform)
{
    vec4 wrapper = vec4(vector, 1.0);
    return (transform * wrapper).xyz;
}

Ray transformRay(Ray ray, mat4 transform)
{
    vec3 direction = transformVector(ray.origin + ray.direction, transform);
    vec3 origin = transformVector(ray.origin, transform);

    Ray localRay = createRay(
        origin,
        normalize(direction - origin)
    );

    return localRay;
}