vec3 transformVector(vec3 vector, mat4 transform, bool translate)
{
    vec4 wrapper = vec4(vector, 1.0);
    vec3 shifted = (transform * wrapper).xyz;

    if (translate)
        return shifted;

    return shifted - position(transform);
}

Ray transformRayToLocal(Ray ray, mat4 transform)
{
    Ray localRay = createRay(
        transformVector(ray.origin, transform, false),
        transformVector(ray.direction, transform, false)
    );

    return localRay;
}